server:
  port: 23302
spring:
  application:
    name: worker-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      batch-size: 10
      buffer-memory: 33554432
  redis:
    port: 6379
    host: localhost
    database: 12
dubbo:
  application:
    name: worker-service
  registry:
    address: zookeeper://localhost:2181
    group: wordcount
  protocol:
    name: dubbo
    port: 33302
    serialization: gson