server:
  port: 23401
spring:
  application:
    name: wordcount-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
mybatis:
  executor-type: batch

#dubbo:
#  application:
#    name: wordcount-service
#  registry:
#    address: nacos://127.0.0.1:8848
#    username: nacos
#    password: nacos
#  protocol:
#    name: dubbo
#    port: 33305
