server:
  port: 23501
spring:
  application:
    name: reducer-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
#      auto-commit-interval: 1s
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: word-count-reducers
    listener:
      type: batch
      ack-mode: batch
      concurrency: 4

