server:
  port: 23501
spring:
  application:
    name: reducer-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: word-count-reducers
