server:
  port: 23901
spring:
  application:
    name: reducer-service
  redis:
    port: 6379
    host: localhost
    database: 12
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: word-count-reducers
      max-poll-records: 20
    listener:
      type: BATCH
      ack-mode: BATCH
      concurrency: 4
dubbo:
  application:
    name: reducer-service
  registry:
    address: zookeeper://localhost:2181
    group: wordcount
  protocol:
    name: dubbo
    port: 22333
    serialization: gson
